# Generated by Django 5.1.6 on 2025-02-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_notifications_orders',
            field=models.BooleanField(default=False, verbose_name='Получать уведомления о заказах'),
        ),
    ]
