# Generated by Django 5.1.6 on 2025-02-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_get_notifications_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='device',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='ip_address',
        ),
    ]
