# Generated by Django 5.1.6 on 2025-02-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_useractivity_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='percentage_of_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Проценты прибыли работника'),
        ),
    ]
