# Generated by Django 5.1.6 on 2025-02-23 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_percentage_of_profit'),
        ('orders', '0034_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='percentage_of_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=30, max_digits=10, null=True, verbose_name='Процент прибыли работника'),
        ),
        migrations.CreateModel(
            name='PromocodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_usage', to='orders.order', verbose_name='Заказ')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_usage', to='orders.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_usage', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
            },
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
