# Generated by Django 5.1.6 on 2025-02-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_percentage_of_profit_promocodeusage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
