# Generated by Django 5.1.6 on 2025-02-10 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимум')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Максимум')),
                ('adjustment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Градация',
                'verbose_name_plural': 'Градации',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус заказа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип заказа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип заказа',
                'verbose_name_plural': 'Типы заказа',
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_currency', models.CharField(max_length=10, verbose_name='Валюта пользователя')),
                ('exchange_currency', models.CharField(max_length=10, verbose_name='Валюта получения')),
                ('course', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс')),
                ('clean_course', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Чистый курс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('graduations', models.ManyToManyField(related_name='conversions', to='orders.graduation', verbose_name='Градация')),
            ],
            options={
                'verbose_name': 'Конвертация',
                'verbose_name_plural': 'Конвертации',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Номер заказа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Пользователь заплатит')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='По курсу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.orderstatus', verbose_name='Статус заказа')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.ordertype', verbose_name='Тип заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Скидка')),
                ('percent', models.BooleanField(default=False, verbose_name='Если скидка в %')),
                ('activations', models.PositiveIntegerField(default=0, verbose_name='Активаций сейчас')),
                ('max_activations', models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего активаций')),
                ('one_time', models.BooleanField(default=False, verbose_name='Один раз на пользователя')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Можно использовать с')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Можно использовать до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('order_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocodes', to='orders.ordertype', verbose_name='Для типа заказа')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Для пользователя')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='PromocodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата активации')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='orders.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_usages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
            },
        ),
    ]
