# Generated by Django 5.1.6 on 2025-02-25 18:40

import django.db.models.deletion
import django_jsonform.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_currency', models.CharField(max_length=10, verbose_name='Валюта пользователя')),
                ('exchange_currency', models.CharField(max_length=10, verbose_name='Валюта получения')),
                ('course', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс')),
                ('clean_course', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Чистый курс')),
                ('grades', django_jsonform.models.fields.JSONField(verbose_name='Градация')),
                ('enabled', models.BooleanField(default=True, verbose_name='Отображать в списке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Валютная пара',
                'verbose_name_plural': 'Валютные пары',
            },
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=30, unique=True, verbose_name='Номер карты')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Банковская карта',
                'verbose_name_plural': 'Банковские карты',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('order_type', models.CharField(choices=[('study', 'Обучение'), ('exchange', 'Обмен'), ('safepay', 'Самовыкуп')], max_length=20, verbose_name='Тип заказа')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Скидка')),
                ('reuse', models.BooleanField(default=False, verbose_name='Можно использовать несколько раз')),
                ('activations', models.PositiveIntegerField(default=0, verbose_name='Активаций сейчас')),
                ('max_activations', models.PositiveIntegerField(verbose_name='Всего активаций')),
                ('start_at', models.DateTimeField(verbose_name='Можно использовать с')),
                ('end_at', models.DateTimeField(verbose_name='Можно использовать до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='orders.conversion', verbose_name='Валютная пара')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocodes', to='bot.tariff', verbose_name='Тариф обучения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Для пользователя')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Номер заказа')),
                ('type', models.CharField(choices=[('study', 'Обучение'), ('exchange', 'Обмен'), ('safepay', 'Самовыкуп')], max_length=20, verbose_name='Тип заказа')),
                ('status', models.CharField(choices=[('create', 'Создан🆕'), ('pending', 'Ожидание⏳'), ('shipped', 'Отправлен📦'), ('canceled', 'Отменен❌'), ('completed', 'Завершен✅')], default='create', max_length=20, verbose_name='Статус заказа')),
                ('contact', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Пользователь заплатит')),
                ('amount_output', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Пользователь получит')),
                ('exchange_course', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Курс обмена')),
                ('clean_course', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Чистый курс')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Прибыль')),
                ('admin_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Прибыль админа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_orders', to=settings.AUTH_USER_MODEL, verbose_name='Админ')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.conversion', verbose_name='Валютная пара')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bot.tariff', verbose_name='Тариф обучения')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'permissions': [('can_export_data', 'Может экспортировать заказы'), ('can_view_clean_course', 'Может смотреть чистый курс'), ('can_view_profit', 'Может смотреть прибыль')],
            },
        ),
        migrations.CreateModel(
            name='PromocodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_usage', to='orders.order', verbose_name='Заказ')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_usage', to='orders.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_usage', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
            },
        ),
        migrations.CreateModel(
            name='TransactionReceiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Номер ордера')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('exchange_course', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Курс')),
                ('amount_usdt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='USDT')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_r', to='orders.order', verbose_name='Заказ')),
                ('payment_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_r', to='orders.paymentcard', verbose_name='Банковская карта')),
            ],
            options={
                'verbose_name': 'Транзакция получения',
                'verbose_name_plural': 'Транзакции получения',
            },
        ),
        migrations.CreateModel(
            name='TransactionSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Номер ордера')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('exchange_course', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Курс')),
                ('amount_usdt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='USDT')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_s', to='orders.order', verbose_name='Заказ')),
                ('payment_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_s', to='orders.paymentcard', verbose_name='Банковская карта')),
            ],
            options={
                'verbose_name': 'Транзакция отправки',
                'verbose_name_plural': 'Транзакции отправки',
            },
        ),
    ]
