# Generated by Django 5.1.6 on 2025-02-10 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodeusage',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='promocode_usages', to='orders.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
