# Generated by Django 5.1.6 on 2025-02-25 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_transactionsending_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('account_id', models.CharField(max_length=30, unique=True, verbose_name='Номер аккаунта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Аккаунт Alipay',
                'verbose_name_plural': 'Аккаунты Alipay',
            },
        ),
        migrations.AlterField(
            model_name='transactionsending',
            name='payment_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_s', to='orders.alipayaccounts', verbose_name='Банковская карта'),
        ),
    ]
