# Generated by Django 5.1.6 on 2025-02-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прибавка к курсу'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нижний порог'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Верхний порог'),
        ),
    ]
