# Generated by Django 5.1.6 on 2025-02-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_graduation_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Верхний порог'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нижний порог'),
        ),
    ]
