# Generated by Django 5.1.6 on 2025-02-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_transactionsending_alipay_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionsending',
            name='alipay_account',
        ),
    ]
