# Generated by Django 5.1.6 on 2025-02-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_graduation_max_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Отнимается от курса'),
        ),
    ]
