# Generated by Django 5.1.6 on 2025-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_graduation_adjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduation',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='min_amount',
        ),
        migrations.AddField(
            model_name='graduation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма от'),
            preserve_default=False,
        ),
    ]
