# Generated by Django 5.1.6 on 2025-03-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_transactionsending_alipay_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='independent_course',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курс самостоятельного обмена'),
        ),
    ]
