# Generated by Django 5.1.6 on 2025-03-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_conversion_independent_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='independent_course',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Градация самостоятельного обмена'),
        ),
    ]
