# Generated by Django 5.1.6 on 2025-02-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_graduation_max_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocodeusage',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_output',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Пользователь получит'),
            preserve_default=False,
        ),
    ]
