# Generated by Django 5.1.6 on 2025-02-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_promocodeusage_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='one_time',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='percent',
        ),
        migrations.AddField(
            model_name='promocode',
            name='conversion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='orders.conversion', verbose_name='Валютная пара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Скидка (Количество от курса)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='end_at',
            field=models.DateTimeField(verbose_name='Можно использовать до'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_activations',
            field=models.PositiveIntegerField(verbose_name='Всего активаций'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='order_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='orders.ordertype', verbose_name='Для типа заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_at',
            field=models.DateTimeField(verbose_name='Можно использовать с'),
        ),
    ]
