# Generated by Django 5.1.6 on 2025-02-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_promocode_one_time_remove_promocode_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='По курсу'),
        ),
    ]
