# Generated by Django 5.1.6 on 2025-02-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(default='', max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
