# Generated by Django 5.1.6 on 2025-02-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Отображать в списке'),
        ),
    ]
