# Generated by Django 5.1.6 on 2025-02-14 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_bot_text'),
        ('orders', '0013_conversion_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('canceled', 'Отменен'), ('completed', 'Завершен')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='order_type',
            field=models.CharField(choices=[('physical', 'Обучение'), ('digital', 'Обмен'), ('subscription', 'Самовыкуп')], default='physical', max_length=20, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('physical', 'Обучение'), ('digital', 'Обмен'), ('subscription', 'Самовыкуп')], default='physical', max_length=20, verbose_name='Тип заказа'),
        ),
        migrations.RenameField(
            model_name='order',
            old_name='exchange_rate',
            new_name='clean_course',
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_course',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='По курсу'),
        ),
        migrations.AddField(
            model_name='order',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bot.study', verbose_name='Тариф обучения'),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='OrderType',
        ),
    ]
