# Generated by Django 5.1.6 on 2025-02-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_status_alter_promocode_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='clean_course',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Чистый курс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_course',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Курс обмена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('create', 'Создан'), ('pending', 'Ожидание'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('canceled', 'Отменен'), ('completed', 'Завершен')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
