# Generated by Django 5.1.6 on 2025-02-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_clean_course_alter_order_exchange_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversion',
            options={'verbose_name': 'Валютная пара', 'verbose_name_plural': 'Валютные пары'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.conversion', verbose_name='Валютная пара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
