# Generated by Django 5.1.6 on 2025-02-14 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_bot_text'),
        ('orders', '0016_alter_conversion_options_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_output',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Пользователь получит'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.conversion', verbose_name='Валютная пара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bot.study', verbose_name='Тариф обучения'),
        ),
    ]
