# Generated by Django 5.1.6 on 2025-02-14 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_amount_output_alter_order_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.promocode', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('create', 'Создан🆕'), ('pending', 'Ожидание⏳'), ('shipped', 'Отправлен📦'), ('canceled', 'Отменен❌'), ('completed', 'Завершен✅')], default='create', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('study', 'Обучение'), ('exchange', 'Обмен'), ('safepay', 'Самовыкуп')], max_length=20, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='order_type',
            field=models.CharField(choices=[('study', 'Обучение'), ('exchange', 'Обмен'), ('safepay', 'Самовыкуп')], max_length=20, verbose_name='Тип заказа'),
        ),
        migrations.DeleteModel(
            name='PromocodeUsage',
        ),
    ]
