# Generated by Django 5.1.6 on 2025-02-14 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_bot_text'),
        ('orders', '0018_order_promocode_alter_order_status_alter_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocodes', to='bot.study', verbose_name='Тариф обучения'),
        ),
    ]
