# Generated by Django 5.1.6 on 2025-02-14 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_promocode_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='orders.conversion', verbose_name='Валютная пара'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='order_type',
            field=models.CharField(blank=True, choices=[('study', 'Обучение'), ('exchange', 'Обмен'), ('safepay', 'Самовыкуп')], max_length=20, null=True, verbose_name='Тип заказа'),
        ),
    ]
