# Generated by Django 5.1.6 on 2025-02-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_promocode_conversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='order_type',
            field=models.CharField(choices=[('study', 'Обучение'), ('exchange', 'Обмен'), ('safepay', 'Самовыкуп')], default='', max_length=20, verbose_name='Тип заказа'),
            preserve_default=False,
        ),
    ]
