# Generated by Django 5.1.6 on 2025-02-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_promocode_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Прибыль'),
        ),
    ]
