# Generated by Django 5.1.6 on 2025-02-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_category_tariff'),
        ('orders', '0022_order_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='graduations',
        ),
        migrations.AddField(
            model_name='conversion',
            name='grades',
            field=models.JSONField(default=dict, verbose_name='Градация'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bot.tariff', verbose_name='Тариф обучения'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocodes', to='bot.tariff', verbose_name='Тариф обучения'),
        ),
        migrations.DeleteModel(
            name='Graduation',
        ),
    ]
