# Generated by Django 5.1.6 on 2025-02-17 15:15

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_conversion_graduations_conversion_grades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='grades',
            field=django_jsonform.models.fields.JSONField(verbose_name='Градация'),
        ),
    ]
