# Generated by Django 5.1.6 on 2025-02-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_conversion_grades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_export_data', 'Может экспортировать заказы')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
