# Generated by Django 5.1.6 on 2025-02-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_export_data', 'Может экспортировать заказы'), ('can_view_clean_course', 'Может смотреть чистый курс'), ('can_view_receive', 'Может смотреть прибыль')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
