# Generated by Django 5.1.6 on 2025-02-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_paymentcard_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='card_type',
        ),
    ]
