# Generated by Django 5.1.6 on 2025-02-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_remove_paymentcard_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_usdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='USDT'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_course',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Номер ордера'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
    ]
