# Generated by Django 5.1.6 on 2025-02-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_transaction_amount_usdt_transaction_exchange_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcard',
            options={'verbose_name': 'Банковская карта', 'verbose_name_plural': 'Банковские карты'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.paymentcard', verbose_name='Банковская карта'),
        ),
    ]
