# Generated by Django 5.1.6 on 2025-02-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='reuse',
            field=models.BooleanField(default=False, verbose_name='Можно использовать несколько раз'),
        ),
    ]
