# Generated by Django 5.1.6 on 2025-02-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_promocode_reuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Название карты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Номер карты'),
        ),
    ]
