# Generated by Django 5.1.6 on 2025-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_alter_paymentcard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название карты'),
        ),
    ]
