# Generated by Django 5.1.6 on 2025-02-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='message_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='Айди сообщения в боте'),
            preserve_default=False,
        ),
    ]
