# Generated by Django 5.1.6 on 2025-02-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_bot_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Текст на кнопке')),
                ('text', models.TextField(max_length=2048, verbose_name='Текст сообщения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=False, verbose_name='Обучение активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Тариф обучения',
                'verbose_name_plural': 'Тарифы обучения',
            },
        ),
        migrations.AlterField(
            model_name='bot',
            name='message_id',
            field=models.IntegerField(unique=True, verbose_name='ID сообщения в боте'),
        ),
    ]
