# Generated by Django 5.1.6 on 2025-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_study_alter_bot_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='text',
            field=models.TextField(max_length=2048, verbose_name='Текст раздела'),
        ),
    ]
