# Generated by Django 5.1.6 on 2025-02-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_category_tariff'),
        ('orders', '0023_remove_conversion_graduations_conversion_grades_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Study',
        ),
        migrations.AddField(
            model_name='tariff',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff', to='bot.category', verbose_name='Категория'),
        ),
    ]
